import os 
import sys
import pandas as pd

###################################---Step 1: Define all Config Variables---######################################################
input_directory=config["input_directory"]
output_directory=config["output_directory"]
reference_data=config["reference_data"]
sample_file=config["sample_file"]

#########################################---Step 1: Define Wildcard---############################################################
samples_dataframe = pd.read_csv(sample_file)

IDs = list(samples_dataframe['ID'])
print('Running on samples:{}'.format(IDs))

########################################---Step 1: Define Dictionary---###########################################################
#this dictionary maps the sampleIDs in samples_dictionary to their corresponding barcode type
#these values will be passed on to get_barcodes.smk and clean_umis.smk to select further parameters
samples_dictionary = samples_dataframe.set_index("ID")['Type'].to_dict()
barcode_types = [*samples_dictionary.values()]

###########################################---Step 1: Define Rules--##############################################################
include: 'rules/cellranger.smk'
include: 'rules/get_barcodes.smk'
include: 'rules/clean_umis.smk'

rule all:
    input:
        expand(config["output_directory"] + "/" + "{ID}" + "/outs/possorted_genome_bam.bam", ID = IDs),
        expand(config["output_directory"] + "/" + "{ID}" + "/outs/" + "{ID}" + "_get_bc_v3.txt", ID = IDs),
        expand(config["output_directory"] + "/" + "{ID}" + "/outs/" + "{ID}" + "_get_bc_v3_no_G.txt", ID = IDs),
        expand(config["output_directory"] + "/" + "{ID}" + "/outs/" + "{ID}" + "_get_bc_v3_no_G_cleaned_UMI.txt", ID = IDs)

#run his script on the two files he gave us to compare output
#meet with Evin about the stats changes, include Libby
        